<a href="https://colab.research.google.com/github/marcgym2/MachineLearning/blob/main/Tarea_en_clase3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from IPython.display import Markdown

from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
df_measures = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/measures_v2.csv")


In [5]:
df_measures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1330816 entries, 0 to 1330815
Data columns (total 13 columns):
 #   Column          Non-Null Count    Dtype  
---  ------          --------------    -----  
 0   u_q             1330816 non-null  float64
 1   coolant         1330816 non-null  float64
 2   stator_winding  1330816 non-null  float64
 3   u_d             1330816 non-null  float64
 4   stator_tooth    1330816 non-null  float64
 5   motor_speed     1330816 non-null  float64
 6   i_d             1330816 non-null  float64
 7   i_q             1330816 non-null  float64
 8   pm              1330816 non-null  float64
 9   stator_yoke     1330816 non-null  float64
 10  ambient         1330816 non-null  float64
 11  torque          1330816 non-null  float64
 12  profile_id      1330816 non-null  int64  
dtypes: float64(12), int64(1)
memory usage: 132.0 MB


In [13]:
# Definiendo feature y target variable para Regresión
X_reg=df_measures.iloc[:,0:10] # features ...
y_reg=df_measures.iloc[:,11] # Target variable: Torque

u_q    coolant  stator_winding       u_d  stator_tooth  \
0       -0.450682  18.805172       19.086670 -0.350055     18.293219   
1       -0.325737  18.818571       19.092390 -0.305803     18.294807   
2       -0.440864  18.828770       19.089380 -0.372503     18.294094   
3       -0.327026  18.835567       19.083031 -0.316199     18.292542   
4       -0.471150  18.857033       19.082525 -0.332272     18.291428   
...           ...        ...             ...       ...           ...   
1330811 -2.152128  30.721298       45.274497  0.791801     41.934347   
1330812 -2.258684  30.721306       45.239017  0.778900     41.868923   
1330813 -2.130312  30.721312       45.211576  0.804914     41.804819   
1330814 -2.268498  30.721316       45.193508  0.763091     41.762220   
1330815 -2.100158  30.721319       45.132307  0.807309     41.734763   

         motor_speed       i_d       i_q         pm  stator_yoke  
0           0.002866  0.004419  0.000328  24.554214    18.316547  
1           0.000257  0.000606 -0.000785  24.538078    18.314955  
2           0.002355  0.001290  0.000386  24.544693    18.326307  
3           0.006105  0.000026  0.002046  24.554018    18.330833  
4           0.003133 -0.064317  0.037184  24.565397    18.326662  
...              ...       ...       ...        ...          ...  
1330811     0.000380 -2.000169  1.097528  62.147780    38.653720  
1330812     0.002985 -2.000499  1.097569  62.142646    38.656328  
1330813     0.002301 -1.999268  1.098765  62.138387    38.650923  
1330814     0.005662 -2.000999  1.095696  62.133422    38.655686  
1330815     0.004395 -2.000792  1.096487  62.131429    38.660370  

[1330816 rows x 10 columns]

In [14]:
# Import SelectKBest, f_regression 
from sklearn.feature_selection import SelectKBest, f_regression

In [16]:
# fit and transform 
# k numero de features (min 1, max 4)
X_reg_new=SelectKBest(score_func=f_regression, k=3).fit_transform(X_reg,y_reg)


In [17]:
# Mejores features
print(X_reg_new[:5])

[[-3.50054592e-01  4.41913679e-03  3.28102178e-04]
 [-3.05803001e-01  6.05872367e-04 -7.85352662e-04]
 [-3.72502625e-01  1.28958712e-03  3.86468193e-04]
 [-3.16198707e-01  2.55843261e-05  2.04566098e-03]
 [-3.32272142e-01 -6.43167794e-02  3.71837765e-02]]


In [18]:
# Con lo anterior, podemos relacionar que los mejores features son u_d, i_d, i_q
print(X_reg.head())

        u_q    coolant  stator_winding       u_d  stator_tooth  motor_speed  \
0 -0.450682  18.805172       19.086670 -0.350055     18.293219     0.002866   
1 -0.325737  18.818571       19.092390 -0.305803     18.294807     0.000257   
2 -0.440864  18.828770       19.089380 -0.372503     18.294094     0.002355   
3 -0.327026  18.835567       19.083031 -0.316199     18.292542     0.006105   
4 -0.471150  18.857033       19.082525 -0.332272     18.291428     0.003133   

        i_d       i_q         pm  stator_yoke  
0  0.004419  0.000328  24.554214    18.316547  
1  0.000606 -0.000785  24.538078    18.314955  
2  0.001290  0.000386  24.544693    18.326307  
3  0.000026  0.002046  24.554018    18.330833  
4 -0.064317  0.037184  24.565397    18.326662  
